"""empty message

Revision ID: 7e36acd7b94a
Revises: 
Create Date: 2019-06-17 19:58:22.618837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e36acd7b94a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radios', sa.Column('preset', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radios', 'preset')
    # ### end Alembic commands ###
